name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    - name: Nuget pack
      run: dotnet pack -c Release -o out -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
    - name: Nuget publish
      run: dotnet nuget push ./out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} -p:PackageID=Norske.Fodselsnummer --no-symbols true --skip-duplicate
